### ISSUE TITLE
Update for Dart 2, Flutter 1.0?

### ISSUE THREAD

**Issue by clarkezone** [angel-example/flutter#3]
I’ve been trying to follow along with this tutorial:

https://dart.academy/building-a-real-time-chat-app-with-angel-and-flutter/

but everything is so out of date that I’ve given up.  Do you plan on updating any time soon?

**Comment by thosakwe** [comment]
This tutorial will eventually receive an update and be found in https://github.com/angel-dart/examples-v2. It was written in July of 2017, so it's only naturally that it would be outdated after all the changes 2018 brought to Dart.

For the time being, though, my priority is finally finishing the remaining parts of Angel 2.0, and updating the documentation. Afterwards, I'll finish the `examples-v2` repository.

Consider joining the chat in the meantime, though, so that you can monitor the progress: https://gitter.im/angel_dart/discussion

It's fairly active, so if you have any questions, they can be answered. I have notifications on my phone as well, so I usually answer within a few minutes, if I'm not asleep or otherwise busy.
